version: '3.3'

services:

  db:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata #primera parte es el disco duro del servidor, segunda parte es donde se encuentra la data dentro del contenedor.
    environment:
      POSTGRES_PASSWORD: PabloPena
      POSTGRES_DB: PabloPena
      POSTGRES_USER: PabloPena
      PGDATA: /var/lib/postgresql/data/pgdata
